version: '3'
services:
  api:
    image: bayugrafit/kairos-image:latest
    restart: always
    ports:
      - 1515:1515
    env_file:
      - .env.development
    command: ["pnpm", "run", "dev"]

  worker:
    image: bayugrafit/kairos-image:latest
    restart: always
    env_file:
      - .env.development
    command: ["pnpm", "run", "dev:worker"]

  dbpgsql:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: rollstacking
      POSTGRES_PASSWORD: rollstacking-2025