const MODE_PAYER_AND_SUBJECT_ARE_THE_SAME = 0b00000001;
const MODE_PUBLISHER_PAYMENT_AND_STAKE_OFFER_REWARD_ARE_THE_SAME = 0b00000010;
const MODE_STAKE_OFFER_STAKED_AND_REWARD_ARE_THE_SAME = 0b00000100;

const UNINITIATED_PDA_TYPE = new Uint8Array([0]);
const CLOSED_PDA_TYPE = new Uint8Array([1]);
const PUBLISHER_PDA_TYPE = new Uint8Array([2]);
const STAKE_OFFER_PDA_TYPE = new Uint8Array([3]);
const STAKE_OFFER_STAKED_PDA_TYPE = new Uint8Array([5]);
const STAKE_OFFER_REWARD_PDA_TYPE = new Uint8Array([4]);
const STAKE_PDA_TYPE = new Uint8Array([6]);

const PUBLISHER_CREATED_EVENT = new Uint8Array([0]);
const PUBLISHER_UPDATED_EVENT = new Uint8Array([1]);
const PUBLISHER_UPDATE_AUTHORITY_CLAIMED_EVENT = new Uint8Array([2]);
const PUBLISHER_WITHDRAWAL_EVENT = new Uint8Array([3]);
const STAKE_OFFER_CREATED_EVENT = new Uint8Array([4]);
const STAKE_OFFER_WITHDRAWAL_EVENT = new Uint8Array([5]);
const STAKE_INIT_EVENT = new Uint8Array([6]);
const STAKE_CLAIM_EVENT = new Uint8Array([7]);
const STAKE_UNSTAKE_EVENT = new Uint8Array([8]);

const PUBLISHER_INIT_TAG = 0;
const PUBLISHER_UPDATE_TAG = 1;
const PUBLISHER_UPDATE_AUTHORITY_CLAIM_TAG = 2;
const PUBLISHER_PAYMENT_WITHDRAWAL_TAG = 3;
const STAKE_OFFER_INIT_TAG = 4;
const STAKE_OFFER_WITHDRAWAL_TAG = 5;
const STAKE_INIT_TAG = 6;
const STAKE_CLAIM_TAG = 7;
const STAKE_UNSTAKE_TAG = 8;
const PDA_DATA_SET_TAG = 255;

module.exports = {
    MODE_PAYER_AND_SUBJECT_ARE_THE_SAME,
    MODE_PUBLISHER_PAYMENT_AND_STAKE_OFFER_REWARD_ARE_THE_SAME,
    MODE_STAKE_OFFER_STAKED_AND_REWARD_ARE_THE_SAME,
    UNINITIATED_PDA_TYPE,
    CLOSED_PDA_TYPE,
    PUBLISHER_PDA_TYPE,
    STAKE_OFFER_PDA_TYPE,
    STAKE_OFFER_STAKED_PDA_TYPE,
    STAKE_OFFER_REWARD_PDA_TYPE,
    STAKE_PDA_TYPE,
    PUBLISHER_CREATED_EVENT,
    PUBLISHER_UPDATED_EVENT,
    PUBLISHER_UPDATE_AUTHORITY_CLAIMED_EVENT,
    PUBLISHER_WITHDRAWAL_EVENT,
    STAKE_OFFER_CREATED_EVENT,
    STAKE_OFFER_WITHDRAWAL_EVENT,
    STAKE_INIT_EVENT,
    STAKE_CLAIM_EVENT,
    STAKE_UNSTAKE_EVENT,
    PUBLISHER_INIT_TAG,
    PUBLISHER_UPDATE_TAG,
    PUBLISHER_UPDATE_AUTHORITY_CLAIM_TAG,
    PUBLISHER_PAYMENT_WITHDRAWAL_TAG,
    STAKE_OFFER_INIT_TAG,
    STAKE_OFFER_WITHDRAWAL_TAG,
    STAKE_INIT_TAG,
    STAKE_CLAIM_TAG,
    STAKE_UNSTAKE_TAG,
    PDA_DATA_SET_TAG
}